### ISSUE TITLE
csld main not found

### ISSUE THREAD

**Issue by Tdub1229** [LLNL/csld#2]
After updating and reinstalling csld, I know get this error... There are a few warning in the installation, but no errors where detected and everything looks to be right. Just trying to move forward. Thank you for your time,

ed@ed-MacBookAir:~/csld_1/csld/examples/Si$ csld_main -f csld.in
csld_main: command not found

**Comment by feifzhou** [comment]
That's a problem of your OS/python installation. Make sure you have the
path properly setup. Typically $HOME/.local/bin
